runs:
  - name: ""
    model_path: ""
    port: 8000
    output_dir: ""
    tp_dp_pairs:
      - tp: 0
        dp: 0
        pp: 0
    context_size: []
    concurrency: []
    num_prompts: []
    output_len: []

  - name: ""
    model_path: ""
    port: 8000
    output_dir: ""
    tp_dp_pairs:
      - tp: 0
        dp: 0
        pp: 0
    context_size: []
    concurrency: []
    num_prompts: []
    output_len: []
